Prepared input files for system tnks2
OpenFreeEnergy/IndustryBenchmarks2024 pull request #106
Opened 2024-07-29 15:28 UTC by Lili-Cao

## Input submission checklist

* [ ] created a directory for each system based on the [template directory][templates]
* [ ] named and placed the directory with the following pattern: `input_structures/prepared_structures/<set_name>/<system_name>`

For each submitted directory:

* [ ] filled in system preparation details in the `PREPARATION_DETAILS.md` file
* [ ] added a PDB file with the protein named `protein.pdb`
* [ ] removed any cofactors from the PDB file and placed them in `cofactors.sdf`
* [ ] did not re-protonate the residues, but left protonation state of the protein unchanged
* [ ] kept cystallographic waters and metals in the PDB file
* [ ] tested the PDB and, if available, cofactors.sdf file using the [input validation script][input_validation]
* [ ] copied over the ligands SDF file to a file named `ligands.sdf` and removed any duplicate binding modes or protonation states, keeping the more favorable state

## Summary of changes

## Licensing agreement
* [ ] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

2024-07-30 08:14 UTC, hannahbaumann requested changes
Thank you @Lili-Cao for submitting the prepared system! I added some comments, please let me know if you have any questions!

2024-07-30 08:14 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/protein.pdb
Just a few things:
- I noticed that this `protein.pdb` has less water molecules than the original structure. Would it be possible to add the other crystalllographic waters back in?
- Residues HIS1011, CYS1081, CYS1089, CYS1092 have a different protonation state than in the original structure. Could you change the protonation states for those, keeping the one in the original structure?
- Could you rename the NMA residue (1112A) to NME?
- Could you add the reason for removing the sulfate ions to the preparation details (`PREPARATION_DETAILS.MD` file)?

2024-07-30 09:00 UTC, Lili-Cao commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/protein.pdb
Hi Hannah,

I think I forgot to unchecl the Hbond optimization and also for waters.
I have pushed my changes according to your comments.
SO4 were kept in the pdb structure also.
But when I run input_validation.py step,  I got the following error: 

ValueError: No template found for residue 214 (SO4).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template

2024-07-30 13:34 UTC, IAlibay requested changes
Thanks so much for submitting this @Lili-Cao! There's a few extra things I noticed when reviewing.

2024-07-30 13:34 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/protein.pdb
Unfortunately SO4 isn't part of the standard ion force field set, so we will have to treat it as a separate co-factor if kept. Here you will need to extract the SO4 to an SDF file (named `cofactors.sdf`).

2024-07-30 13:34 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/protein.pdb
Unlike the other termini (which are capped), I noticed that both GLY 952 and MET 1115 are uncapped (NH3) in the original schrodinger structure. These both would likely form some kind of charged interaction with the SO4 cofactors. Is there a reason for capping these?

2024-07-30 13:34 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/PREPARATION_DETAILS.md
These instructions might need updating depending on what is done with SO4 and some of the caps.

2024-07-31 07:16 UTC, Lili-Cao commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/protein.pdb
GLY A 952 and MET 1115 are quite far from the SO4 but I can change them back to the original structure. I think maestro  changed them to NH3.

2024-08-05 07:48 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/protein.pdb
@Lili-Cao thank you, yes that would be great!

2024-08-05 08:53 UTC, hannahbaumann commented
Thank you @Lili-Cao , this looks good! I just noticed that the two termini that you changed (GLY A 952 and MET 1115) don't have a charged nitrogen but just an NH. Would it be possible if you could make those residues charged, meaning an NH3+? Thank you!

2024-08-12 10:01 UTC, IAlibay requested changes
Sorry @Lili-Cao, just the one thing for me - the merged SO4 in the cofactors.sdf is likely going to cause issues during partial charge generation.

2024-08-12 10:01 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/cofactors.sdf
The behaviour of having two fragments in one molecule is a little bit undefined, especially for AM1-BCC partial charge generation.

Could you split the two SO4 into separate entries in the SDF please?

2024-08-16 12:26 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/cofactors.sdf
@Lili-Cao : I'm so sorry, I hadn't seen that the SO4 was in a single residue. Would it be possible to separate them? Please let us know if you need any help!

2024-08-22 20:01 UTC, IAlibay requested changes
So sorry to ping you on this again @Lili-Cao, it looks like the cofactor files you created (cofactors1.sdf and cofactors2.sdf), now include the entire PDB file? I'm not sure what happened here.

I think it should be just a case of splitting the `cofactors.sdf` file into two. Happy to jump on a call and help with this if necessary.

2024-09-03 10:55 UTC, hannahbaumann requested changes
Thanks @Lili-Cao ! I noticed that now there are three files for the cofactors and to me the file `cofactor1.sdf` looks best! Please let me know if you need help removing the other two files and renaming this one or if you have any questions!

2024-09-03 10:55 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/cofactor1.sdf
This `cofactor1.sdf` file looks great to me as it has both SO4 ions and they are separated in the sdf! 
I think it would make sense to delete the other two files, `cofactors.sdf` and `cofactor2.sdf` and afterwards to rename this file to `cofactors.sdf`. Please let me know if it would be easiest if I deleted them here or if you want to remove them using `git rm` and then `git commit`!

2024-09-03 10:55 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/cofactor2.sdf
I think this file can be removed, see my comment above.

2024-09-03 10:55 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/merck/tnks2/cofactors.sdf
I think this file can be removed, see my comment above.

2024-09-10 16:30 UTC, hannahbaumann approved these changes
Thanks @Lili-Cao , this looks great to me!

2024-09-11 17:38 UTC, merged