Add JACS CKD2 inputs
OpenFreeEnergy/IndustryBenchmarks2024 pull request #107
Opened 2024-07-29 18:54 UTC by IAlibay

## Input submission checklist

* [x] created a directory for each system based on the [template directory][templates]
* [x] named and placed the directory with the following pattern: `input_structures/prepared_structures/<set_name>/<system_name>`

For each submitted directory:

* [x] filled in system preparation details in the `PREPARATION_DETAILS.md` file
* [x] added a PDB file with the protein named `protein.pdb`
* [x] removed any cofactors from the PDB file and placed them in `cofactors.sdf`
* [ ] did not re-protonate the residues, but left protonation state of the protein unchanged
* [x] kept cystallographic waters and metals in the PDB file
* [x] tested the PDB and, if available, cofactors.sdf file using the [input validation script][input_validation]
* [x] copied over the ligands SDF file to a file named `ligands.sdf` and removed any duplicate binding modes or protonation states, keeping the more favorable state

## Summary of changes

## Licensing agreement
* [x] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

2024-07-29 19:00 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/jacs_set/cdk2/protein.pdb
The one thing I did notice was that the protons seems to have been re-added, there's no significant changes, but the steps seems to have re-assigned everything.

2024-07-29 19:00 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/jacs_set/tyk2/ligands.sdf
This is just a permissions change on the file, it had executable permissions on so I did `chmod -x` on it.

2024-07-30 07:34 UTC, hannahbaumann requested changes
Just the one comment, otherwise looks good to me!

2024-07-30 07:34 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/jacs_set/cdk2/protein.pdb
Should the two NMA residues be renamed to NME?

2024-07-30 12:58 UTC, IAlibay commented
@hannahbaumann caps have been renamed & resids fixed

2024-07-31 07:59 UTC, hannahbaumann approved these changes
Thanks, lgtm!

2024-07-31 08:55 UTC, merged