Prepared input files for fragments/jak2_set1 system
OpenFreeEnergy/IndustryBenchmarks2024 pull request #126
Opened 2024-08-15 05:05 UTC by BillSwope

## Input submission checklist

* [x ] created a directory for each system based on the [template directory][templates]
* [x ] named and placed the directory with the following pattern: `input_structures/prepared_structures/<set_name>/<system_name>`

For each submitted directory:

* [x ] filled in system preparation details in the `PREPARATION_DETAILS.md` file
* [x] added a PDB file with the protein named `protein.pdb`
* [x ] removed any cofactors from the PDB file and placed them in `cofactors.sdf`
* [x ] did not re-protonate the residues, but left protonation state of the protein unchanged
* [x] kept cystallographic waters and metals in the PDB file
* [x ] tested the PDB and, if available, cofactors.sdf file using the [input validation script][input_validation]
* [x ] copied over the ligands SDF file to a file named `ligands.sdf` and removed any duplicate binding modes or protonation states, keeping the more favorable state

## Summary of changes
Protein: added NME/ACE capping groups; changes phosphate from tyrosine (PTR -> TYR); removed one water that was clashing with NME; rename NMA->NME.
Ligand: removed two ligands: 4b and "3 althernative".  4b was an alternate protonation state of 4a, which had the stronger binding energy; "3 alternative" was a different binding pose of "3", but Schrodinger did not report a dG for this "3 alternative"

## Licensing agreement
* [x ] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

2024-08-15 08:11 UTC, hannahbaumann requested changes
Thanks @BillSwope , this looks good to me, just the one comment!

2024-08-15 08:11 UTC, hannahbaumann commented on industry_benchmarks/input_structures/prepared_structures/fragments/jak2_set1/protein.pdb
I noticed that for the two CYS residues 917 and 961 there are two alternate conformations. Could you potentially remove one of them such that the pdb has only a single conformation?

2024-08-15 08:22 UTC, BillSwope commented
Sure, thanks!  I didn't even notice this!  I don't suppose it matters which
conformation I take, right?

What about the jak2_set1 that Binqing submitted?  I have not seen it.

Regards...Bill

On Thu, Aug 15, 2024 at 1:11 AM Hannah Baumann ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks @BillSwope <https://github.com/BillSwope> , this looks good to me,
> just the one comment!
> ------------------------------
>
> On
> industry_benchmarks/input_structures/prepared_structures/fragments/jak2_set1/protein.pdb
> <https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/126#discussion_r1718101994>
> :
>
> I noticed that for the two CYS residues 917 and 961 there are two
> alternate conformations. Could you potentially remove one of them such that
> the pdb has only a single conformation?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/126#pullrequestreview-2239923428>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARBVQIAKTFTFA5BDSASS2NLZRRPDHAVCNFSM6AAAAABMRSK3KWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMZZHEZDGNBSHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-08-15 08:32 UTC, hannahbaumann commented
Thanks @BillSwope , I noticed that there are additional residues with alternate conformations: Val916, ILE982, Arg1117. The pdb file from Schrodinger contains the occupancy of the two states (the column after the z coordinate), could you keep the conformation with the higher occupancy (e.g. for VAL 916 the A-state is 65% while B-state is 35%).
Binqing only kept a single conformation, however there are some other changes needed for that preparation (e.g. keeping crystallographic waters). Maybe you could talk about it and let us know which submission we should include here?

2024-08-15 10:42 UTC, hannahbaumann approved these changes
Thanks @BillSwope , this looks good to me!

2024-08-22 13:19 UTC, IAlibay approved these changes
Thanks @BillSwope !

2024-08-22 13:19 UTC, merged