Add check for missing result .json files
OpenFreeEnergy/IndustryBenchmarks2024 pull request #150
Opened 2024-09-19 08:33 UTC by hannahbaumann

## Licensing agreement
* [x] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

2024-09-19 08:33 UTC, pep8speaks commented
Hello @hannahbaumann! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`industry_benchmarks/utils/extras/extract_results.py`](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/13f3607903ecf81e7b73a4a59cc982bc49b58b37/industry_benchmarks/utils/extras/extract_results.py):

> [Line 136:80](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/13f3607903ecf81e7b73a4a59cc982bc49b58b37/industry_benchmarks/utils/extras/extract_results.py#L136): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 150:80](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/13f3607903ecf81e7b73a4a59cc982bc49b58b37/industry_benchmarks/utils/extras/extract_results.py#L150): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 176:80](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/13f3607903ecf81e7b73a4a59cc982bc49b58b37/industry_benchmarks/utils/extras/extract_results.py#L176): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 301:80](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/13f3607903ecf81e7b73a4a59cc982bc49b58b37/industry_benchmarks/utils/extras/extract_results.py#L301): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2024-09-19 09:35 UTC, hannahbaumann commented on industry_benchmarks/utils/extras/extract_results.py
> +        "Total number of transformations (both solvent and complex): "
```suggestion
        "Total number of transformations that should have completed (both solvent and complex): "
```

2024-09-24 11:16 UTC, IAlibay requested changes
Couple of things, mostly removing an errand method and clarifying a message. Otherwise lgtm.

2024-09-24 11:16 UTC, IAlibay commented on industry_benchmarks/utils/extras/extract_results.py
> +        )
```suggestion
            "    - Number of transformations without output "
            f"results files: {len(missing_files)}"
        )
```
Something like that

2024-09-24 11:16 UTC, IAlibay commented on industry_benchmarks/utils/extras/extract_results.py
> +        f"{len(input_ligand_network.edges)*2}"
A reminder to re-visit this once we look at "fixed" networks.

2024-09-24 11:16 UTC, IAlibay requested changes
Couple of things, mainly removing an extra method and clarifying an error message.

2024-09-24 14:05 UTC, IAlibay approved these changes
lgtm!

2024-09-24 14:05 UTC, merged