Asap bace
OpenFreeEnergy/IndustryBenchmarks2024 pull request #154
Opened 2024-10-04 19:43 UTC by mikemhenry

## Input submission checklist

* [ ] created a directory for each system based on the [template directory][templates]
* [ ] named and placed the directory with the following pattern: `input_structures/prepared_structures/<set_name>/<system_name>`

For each submitted directory:

* [ ] filled in system preparation details in the `PREPARATION_DETAILS.md` file
* [ ] added a PDB file with the protein named `protein.pdb`
* [ ] removed any cofactors from the PDB file and placed them in `cofactors.sdf`
* [ ] did not re-protonate the residues, but left protonation state of the protein unchanged
* [ ] kept cystallographic waters and metals in the PDB file
* [ ] tested the PDB and, if available, cofactors.sdf file using the [input validation script][input_validation]
* [ ] copied over the ligands SDF file to a file named `ligands.sdf` and removed any duplicate binding modes or protonation states, keeping the more favorable state

## Summary of changes

## Licensing agreement
* [ ] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

2024-10-05 09:44 UTC, IAlibay requested changes
There's some issues with the keranen_p2 structure that need to be addressed (it looks like the wrong input file!)

2024-10-05 09:44 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/ciordia_retro/protein.pdb
There are 3 disulfide bonds that aren't in the TER record, whilst OpenMM does add them in, it would be good if you could manually also place them in the PDB file.

Here is the warning record: 

WARNING: unbonded disulfide bridge found: <Atom 5630: SG of type S of resname CYS, resid 407 and segid A and altLoc > and <Atom 2445: SG of type S of resname CYS, resid 203 and segid A and altLoc >
WARNING: unbonded disulfide bridge found: <Atom 5972: SG of type S of resname CYS, resid 430 and segid A and altLoc > and <Atom 3405: SG of type S of resname CYS, resid 265 and segid A and altLoc >
WARNING: unbonded disulfide bridge found: <Atom 5017: SG of type S of resname CYS, resid 367 and segid A and altLoc > and <Atom 4224: SG of type S of resname CYS, resid 317 and segid A and altLoc >
WARNING: unbonded disulfide bridge found: <Atom 4224: SG of type S of resname CYS, resid 317 and segid A and altLoc > and <Atom 5017: SG of type S of resname CYS, resid 367 and segid A and altLoc >
WARNING: unbonded disulfide bridge found: <Atom 2445: SG of type S of resname CYS, resid 203 and segid A and altLoc > and <Atom 5630: SG of type S of resname CYS, resid 407 and segid A and altLoc >
WARNING: unbonded disulfide bridge found: <Atom 3405: SG of type S of resname CYS, resid 265 and segid A and altLoc > and <Atom 5972: SG of type S of resname CYS, resid 430 and segid A and altLoc >

2024-10-05 09:44 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/keranen_p2/protein.pdb
This protein doesn't match the original input structure:
- The coordinates don't match (completely unaligned structures)
  - The ligands don't fit in the binding site at all.
- There's a whole missing loop

Did you maybe use the wrong input structure?

2024-10-07 20:40 UTC, mikemhenry commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/keranen_p2/protein.pdb
:see_no_evil: the keranen p2 pdb was the one that you did to show me how it is done https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/154/commits/950382fd1429584e253aeb4a7e9ac5407aa5894b -- but it does sound like we used the wrong starting input file? Looking at https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/main/industry_benchmarks/input_structures/original_structures/janssen_bace/bace_keranen_p2_protein.pdb it looks fine in terms of the ligands fitting in the binding pocket, so we must have really mangled it on our first try.

I will re-prep it

2024-10-07 20:42 UTC, mikemhenry commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/ciordia_retro/protein.pdb
I didn't see those warnings when I ran the `utils/input_validation.py` script -- can you let me know what you did to check this? I can fix the records but I want to make sure they are good before I ping for another review

2024-10-09 18:06 UTC, mikemhenry commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/keranen_p2/protein.pdb
Okay I think it has been fixed now!

2024-10-11 08:58 UTC, IAlibay requested changes

2024-10-11 08:58 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/ciordia_retro/protein.pdb
We use this script as part of the validation checks: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/blob/main/industry_benchmarks/utils/maint/check_protein_prep.py

Specifically here you'd be looking at lines 58 through to 73 which loop through all the SG atoms and check if they could be making bonds to surrounding SG atoms.

2024-10-11 19:19 UTC, mikemhenry commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/ciordia_retro/protein.pdb
I think I am the last one through this so its probably too late but we should then add running that script as a step in our PR template.

2024-10-11 19:47 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/ciordia_retro/protein.pdb
No - it's too noisy / complicated (because it will spit out things that seem like errors but are ok). The expert evaluation of the output is too complicated to have folks rely on it.

2024-10-11 19:51 UTC, IAlibay commented on industry_benchmarks/input_structures/prepared_structures/janssen_bace/keranen_p2/protein.pdb
oops my bad this is fine!

2024-10-21 12:23 UTC, merged