Add documentation for the fix_network script
OpenFreeEnergy/IndustryBenchmarks2024 pull request #157
Opened 2024-10-09 08:59 UTC by hannahbaumann

## Licensing agreement
* [ ] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

2024-10-10 15:44 UTC, jthorton approved these changes
LGTM!

2024-10-11 07:59 UTC, hannahbaumann commented
@jthorton I made a small update, reflecting that now we're saving only the new edges in the `ligand_network.graphml` file, not the full network.

2024-10-11 09:29 UTC, jthorton approved these changes
Looks great!

2024-10-11 09:29 UTC, jthorton commented on docs/source/public/overview.rst
> +  * Add a new edge to the network. We provide a script that will automatically find a suitable new edge, more information can be found :ref:`here <fix_networks>`.
Good job I missed that one!

2024-10-11 11:01 UTC, IAlibay commented on docs/source/public/overview.rst
> +If removing a reproducibly failing edge leads to a disconnected graph, new edges need to be added in order to fix the broken network.
How would they know that this is a broken network? I.e. number of ligands lower than expected, failure during the analysis scripts....

2024-10-11 11:03 UTC, IAlibay requested changes
Very quick review.

2024-10-11 11:03 UTC, IAlibay commented on docs/source/public/overview.rst
> +The fixing of disconnected networks is carried out using the script provided under
```suggestion
This can be achieved using the script provided under
```

2024-10-11 11:03 UTC, IAlibay commented on docs/source/public/overview.rst
> +The script finds new edges to repair the disconnected network and produces the inputs necessary to run those additional edges.
How many new edges?

2024-10-11 11:03 UTC, IAlibay commented on docs/source/public/overview.rst
> +The script takes as inputs the ``AlchemicalNetwork`` from the original setup, the result ``.json`` files, and the folder name for storing the outputs.
Where should they expect to find this if they use the default instructions we gave them?

2024-10-11 11:03 UTC, IAlibay commented on docs/source/public/overview.rst
> +The ``new_edges`` folder also contains a ``ligand_network.graphml`` file as well as an ``alchemical_network.json`` file containing the serialized version of the new ``LigandNetwork`` and ``Alchemical
Clarify that this is only for the additional edges not the full new network?

2024-10-16 11:46 UTC, merged